/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Espressif IoT Development Framework Configuration
 *
 */
#define CONFIG_BLUEDROID_MEM_DEBUG 0
//#define CONFIG_HCI_INITIAL_TRACE_LEVEL 5
//#define CONFIG_BTM_INITIAL_TRACE_LEVEL 5
//#define CONFIG_RFCOMM_INITIAL_TRACE_LEVEL 5
//#define CONFIG_SDP_INITIAL_TRACE_LEVEL 5
//#define CONFIG_GAP_INITIAL_TRACE_LEVEL 5
//#define CONFIG_BTC_INITIAL_TRACE_LEVEL 5
//#define CONFIG_OSI_INITIAL_TRACE_LEVEL 5
//#define CONFIG_BLUFI_INITIAL_TRACE_LEVEL 5
//#define CONFIG_SMP_INITIAL_TRACE_LEVEL 5
//#define CONFIG_APPL_INITIAL_TRACE_LEVEL 5
//#define CONFIG_AVRC_INITIAL_TRACE_LEVEL 5
//#define CONFIG_A2D_INITIAL_TRACE_LEVEL 5
//#define CONFIG_BNEP_INITIAL_TRACE_LEVEL 5
#define CONFIG_HFP_AUDIO_DATA_PATH_HCI 0
#define CONFIG_BT_SPP_ENABLED 0
#define CONFIG_HFP_CLIENT_ENABLE 0
#define CONFIG_BT_STACK_NO_LOG 0
#define CONFIG_GATTC_ENABLE 1
#define CONFIG_GATTS_ENABLE 1
#define CONFIG_SMP_ENABLE 1
#define CONFIG_A2DP_ENABLE 1
#define CONFIG_CLASSIC_BT_ENABLED 1
#define CONFIG_BT_ACL_CONNECTIONS 4
#define CONFIG_LOG_DEFAULT_LEVEL 5
#define CONFIG_BTC_TASK_STACK_SIZE 3072
#define CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY 1
#define CONFIG_BLUETOOTH_RTK
